### ISSUE TITLE
Linux Package

### ISSUE THREAD

**Issue by larsnolden** [plotly/falcon-sql-client#153]
I tried to install the database connector on Linux with the latest (2.0.2) zip package.
The install.sh fails on Kubuntu 16.04 with:
```
 chromedriver@2.29.0 install /home/bender/Downloads/linux-plotly-database-connector/database_connector/resources/app/node_modules/chromedriver
 node install.js

module.js:487
    throw err;
    ^

Error: Cannot find module 'fs.realpath'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/bender/Downloads/linux-plotly-database-connector/database_connector/resources/app/node_modules/rimraf/node_modules/glob/glob.js:44:10)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
```

I guess fs.realpath is OS dependent and not applicable for linux?
It would be great to get some feedback on this!

**Comment by n-riesco** [comment]
You can download a prerelease with a fix here, please let us know if you have any issues:
https://github.com/plotly/falcon-sql-client/releases/tag/v2.3-pre

**Comment by n-riesco** [comment]
Fixed in https://github.com/plotly/falcon-sql-client/releases/tag/v2.3.2
