### ISSUE TITLE
test failure in QueryScheduler.spec.js

### ISSUE THREAD

**Issue by n-riesco** [plotly/falcon-sql-client#262]
```
  QueryScheduler
    ✓ executes a function on an interval (2505ms)
    ✓ overwrites interval functions (6510ms)
    ✓ saves queries to file
    ✓ saving a query that already exists updates the query
    ✓ clears and deletes the query if its associated grid was deleted (14287ms)
    1) queries a database and updates a plotly grid on an interval


  26 passing (3m)
  1 pending
  1 failing

  1) QueryScheduler queries a database and updates a plotly grid on an interval:

      AssertionError: expected [ 'Guinea', 'Guinea' ] to deeply equal [ 1 ]
      + expected - actual

       [
      -  "Guinea"
      -  "Guinea"
      +  1
       ]
      
      at Function.assert.deepEqual (node_modules/chai/lib/chai/interface/assert.js:216:32)
      at test/backend/QueryScheduler.spec.js:270:24
      at <anonymous>
      at process._tickDomainCallback (internal/process/next_tick.js:135:7)
```

**Comment by n-riesco** [comment]
Needs a pause after resetting the grid and before verifying the grid has reset: https://github.com/plotly/falcon-sql-client/blob/be10f33e7a19ad17916e6d793d37cac6345f9241/test/backend/QueryScheduler.spec.js#L266
