### ISSUE TITLE
test failure in QueryScheduler.spec.js (race condition)

### ISSUE THREAD

**Issue by n-riesco** [plotly/falcon-sql-client#289]
Test failed because Plotly took more than 1/2 the refresh interval to respond.

We need to rethink how to test the query scheduler to account for responses slower than the refresh interval.

From CircleCI
```
  1) QueryScheduler queries a database and updates a plotly grid on an interval:

      First check
      + expected - actual

       [
      -  "a"
      -  "b"
      -  "c"
      +  "Guinea"
      +  "Guinea"
       ]
      
      at Function.assert.deepEqual (node_modules/chai/lib/chai/interface/assert.js:216:32)
      at test/backend/QueryScheduler.spec.js:222:24
      at <anonymous>
      at process._tickDomainCallback (internal/process/next_tick.js:135:7)
```

This is the relevant code: https://github.com/plotly/falcon-sql-client/blob/cc0b7c3339cc1e67116e81bcc90953c23084c83d/test/backend/QueryScheduler.spec.js#L286-L306

**Comment by n-riesco** [comment]
We need to check the call to `createGrid` was successful before proceeding.

```
  1) Grid API Functions updateGrid overwrites a grid with new data:
     TypeError: Cannot read property 'fid' of undefined
      at test/backend/PlotlyAPI.spec.js:29:19
      at <anonymous>
      at process._tickDomainCallback (internal/process/next_tick.js:135:7)
```

Relevant code: https://github.com/plotly/falcon-sql-client/blob/adaca9d530ef48c43a08249f6d1d8f7ae153dbad/test/backend/PlotlyAPI.spec.js#L27-L30
